- hosts: all
  gather_facts: no
  connection: network_cli
  max_fail_percentage: 0

  tasks:
    - name: gather facts config
      ax_facts:
        gather_subset:
          - "all"

    - name: parse running-config
      set_fact:
        acl_config: "{{ ansible_net_config | parse_cli_textfsm( template ) }}"

    - name: check ACL config
      assert:
        that:
          - "'{{ add_acl_seq }} {{ add_acl_entry }}' ==  '{{ item.1 }}'"
      when: item.1 | match( "^" + add_acl_seq + " ")
      with_subelements:
        - "{{ acl_config }}"
        - AclEntry


    - name: add ACL config
      ax_config:
        lines:
          - "{{ add_acl_seq }} {{ add_acl_entry }}"
        parents: "ip access-list extended {{ item.AclName }}"
        save_when: modified
      with_items: "{{ acl_config }}"

