- hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ax
    ansible_user: alaxala
    ansible_password: alaxala
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: alaxala

  tasks:
    - name: configure interface
      ax_config:
        lines:
          - switchport access vlan 100
        parents: interface gigabitethernet {{ item }}
      with_items:
        - 1/0/5
        - 1/0/7
